#!/usr/bin/env ruby
# -*- coding: utf-8 -*-

require 'r-fxxk'

class Nyaruko < Brainfuck
  nxt 'きら'
  inc 'あこ'
  prv 'ゆめ'
  dec 'ロラ'
  opn 'アイ！'
  cls 'カツ！'
  put "面白いじゃない！"
  get 'おす！'
end

puts Nyaruko.new.fuck(ARGF.read)

